GET http://localhost:3000/hotels


###

GET http://localhost:3000/reservations


###

POST http://localhost:3000/reservations
Content-Type: application/json

{
    "hotelID": 1,
    "fullName": "Gregor Dzierzon",
    "checkinDate": "12/10/2022",
    "checkoutDate": "12/12/2022",
    "guests": 2
}

###

GET http://localhost:3000/reservations/707


###

PATCH http://localhost:3000/reservations/707
Content-Type: application/json

{
    "guests": 3
}

###

PUT http://localhost:3000/reservations/707
Content-Type: application/json

{
    "hotelID": 1,
    "fullName": "Gregor Dzierzon",
    "checkinDate": "12/09/2022",
    "checkoutDate": "12/13/2022",
    "guests": 2,
    "id": 138
}



###

DELETE http://localhost:3000/reservations/707


###

GET https://swapi.dev/api/people


###

GET https://swapi.dev/api/people?page=2

